namespace DAGServer
{
    public class ServerPacket
    {
        public enum ServerPacketType        //Packets that the server sends
        {
            GivePing,
            GiveID,
            GiveClientInfo,
            GiveClientCharacterType,
            GiveAllClientData,
            GivePlayerDataDeletion,
            GiveClientMovementInformation,
            SendPlayerVariableData,
            PlaySound,
            GiveStringMessageToOtherPlayers,
            SendWorldArrayToAll,
            SendUpdatedMapObject,
            SendMapObjectDestruction,
            SendNewEnemyInfo,
            SendNewProjectileInfo,
            SendEnemyVariableData,
            SendEnemyAilment,
            SendEnemyDeath,
            SendProjectileVariableData,
            SendPlayerUsedItem,
            SendOtherPlayerDoneLoading,
            SendAllPlayerSpawnDataToOthers,
            SendNewItemCreation,
            SendItemDeletion,
            ReceiveEnemyListSync,
            SendRequestedEnemyData,
            SendEnemyData
        }

        public enum ClientPacketType        //Packets that the clients send
        {
            SendPing,
            RequestID,
            SendClientInfo,
            SendClientCharacterType,
            RequestAllClientData,
            RequestPlayerDataDeletion,
            SendMovementInformation,
            SendPlayerVariableData,
            SendSound,
            SendStringMessageToOtherPlayers,
            SendWorldArray,
            SendUpdatedMapObject,
            SendMapObjectDestruction,
            SendNewEnemyInfo,
            SendEnemyVariableData,
            SendEnemyAilment,
            SendEnemyDeletion,
            SendNewProjectileInfo,
            SendProjectileVariableData,
            SendPlayerUsedItem,
            SendDoneLoading,
            SendAllPlayerSpawnData,
            SendNewItemCreation,
            SendItemDeletion,
            SendEnemyListForSync,
            RequestEnemyData,
            SendEnemyData
        }
    }
}
